development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url:  postgres://odnhjhbunukdhp:3uTqM5ms0cJP75aRIRhQOeuU3i@ec2-54-243-249-149.compute-1.amazonaws.com:5432/de6iajtiqfi36g

